export const TOOLS = [
  {
    id: 'pdf-splitter',
    label: 'PDF Splitter',
    description: 'Split any multi-page PDF into individual pages.',
    icon: '📄',
    category: 'PDF',
    path: '/tools/pdf-splitter',
    accent: '#EF4444',
    live: true,
    component: () => import('../components/tools/PdfSplitter.jsx'),
  },
  {
    id: 'image-converter',
    label: 'Image to WebP',
    description: 'Convert JPG and PNG to WebP for faster, leaner websites.',
    icon: '🖼️',
    category: 'Image',
    path: '/tools/image-converter',
    accent: '#F59E0B',
    live: true,
    component: () => import('../components/tools/ImageOptimizer.jsx'),
  },
  {
    id: 'qr-generator',
    label: 'QR Generator',
    description: 'Generate scannable QR codes from any URL or text.',
    icon: '⬛',
    category: 'Utility',
    path: '/tools/qr-generator',
    accent: '#10B981',
    live: true,
    component: () => import('../components/tools/QrGenerator.jsx'),
  },
  {
    id: 'background-remover',
    label: 'Background Remover',
    description: 'Remove any image background instantly with on-device AI.',
    icon: '✨',
    category: 'Image',
    path: '/tools/background-remover',
    accent: '#8B5CF6',
    live: true,
    component: () => import('../components/tools/BackgroundRemover.jsx'),
  },
  {
    id: 'json-formatter',
    label: 'JSON Formatter',
    description: 'Beautify, validate and minify JSON with syntax highlighting.',
    icon: '{}',
    category: 'Developer',
    path: '/tools/json-formatter',
    accent: '#8B5CF6',
    live: true,
    component: () => import('../components/tools/JsonFormatter.jsx'),
  },
  {
    id: 'social-resizer',
    label: 'Social Resizer',
    description: 'Resize images for Instagram, TikTok and YouTube.',
    icon: '📐',
    category: 'Design',
    path: '/tools/social-resizer',
    accent: '#3B82F6',
    live: true,
    component: () => import('../components/tools/SocialResizer.jsx'),
  },
  {
    id: 'mp4-to-mp3',
    label: 'MP4 to MP3',
    description: 'Extract audio from any video file directly in your browser.',
    icon: '🎵',
    category: 'Audio',
    path: '/tools/mp4-to-mp3',
    accent: '#EC4899',
    live: true,
    component: () => import('../components/tools/Mp4ToMp3.jsx'),
  },
  {
    id: 'unit-converter',
    label: 'Unit Converter',
    description: 'Convert between any units — length, weight, temperature and more.',
    icon: '📏',
    category: 'Developer',
    path: '/tools/unit-converter',
    accent: '#0EA5E9',
    live: true,
    component: () => import('../components/tools/UnitConverter.jsx'),
  },
]

export const LIVE_TOOLS = TOOLS.filter(t => t.live)
